services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb-service:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auction-service:
    image: fsv2860/auction-service:latest
    build: # build context
      context: . # . context is inside root (auctions) directory
      dockerfile: src/AuctionService/Dockerfile
    environment: # overwrites appsettings.json
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 # internal URL our service/application will run on.
      - RabbitMq__Host=rabbitmq # RabbitMq_Host = RabbitMq.Host | rabbitMq = name of the service (defined above).
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=123;Database=auctions # ConnectionStrings.DefaultConnection | server=postgres postgres refers to the name of the service
      - IdentityServiceUrl=http://identity-service
    ports:
      - 7001:80 # source_port:docker_port
    depends_on:
      - postgres # postgres service defined above
      - rabbitmq # rabbitmq service defined above
  search-service:
    image: fsv2860/search-service:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 # internal URL our service/application will run on.
      - RabbitMq__Host=rabbitmq # RabbitMq_Host = RabbitMq.Host | rabbitMq = name of the service (defined above).
      - ConnectionStrings__MongoDbConnection=mongodb://root:123@mongodb-service # @mongodb-service refers to the service (defined above).
      - AuctionServiceUrl="http://auction-service"
    ports:
      - 7002:80
    depends_on:
      - mongodb-service
      - rabbitmq # rabbitmq service defined above
  identity-service:
    image: fsv2860/identity-service:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80 # internal URL our service/application will run on.
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=123;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-service:
    image: fsv2860/gateway-service:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker # reads from appsettings.Docker.json
      - ASPNETCORE_URLS=http://+:80 # internal URL our service/application will run on.
    ports:
      - 6001:80
volumes:
  pgdata:
  mongodata:
